import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
import { db } from '@/lib/db'

export default  async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const user = await db.user.findFirst()
  
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
